using PactNet;
using PactNet.Verifier;
using Xunit;
using Xunit.Abstractions;

namespace LotyApi.Tests.Pact;

/// <summary>
/// PactNet provider verification tests.
/// Verifies that the AeroApi (provider) satisfies the contract
/// defined by AeroFront (consumer).
///
/// To run these tests, first generate the pact file from the consumer side:
///   cd aero-front && npm run test:pact
/// Then run:
///   cd aero-api-tests && dotnet test --filter "FullyQualifiedName~Pact"
/// </summary>
public class AeroApiProviderTests : IDisposable
{
    private readonly PactTestWebAppFactory _factory;
    private readonly ITestOutputHelper _output;

    public AeroApiProviderTests(ITestOutputHelper output)
    {
        _factory = new PactTestWebAppFactory();
        _output = output;
    }

    [Fact(Skip = "Run after consumer pact files are generated: npm run test:pact")]
    public void EnsureAeroApiHonoursAeroFrontPact()
    {
        // The pact file is generated by the consumer (aero-front).
        // Default location: aero-front/pacts/AeroFront-AeroApi.json
        var pactDir = Path.GetFullPath(
            Path.Combine("..", "..", "..", "..", "aero-front", "pacts"));

        // Start the test server
        var client = _factory.CreateClient();
        var uri = client.BaseAddress!;

        var verifier = new PactVerifier("AeroApi", new PactVerifierConfig
        {
            LogLevel = PactLogLevel.Information
        });

        verifier
            .WithHttpEndpoint(uri)
            .WithDirectorySource(new DirectoryInfo(pactDir))
            .WithProviderStateUrl(new Uri(uri, "/provider-states"))
            .Verify();
    }

    public void Dispose()
    {
        _factory.Dispose();
    }
}
